env:
  CIRRUS_CLONE_DEPTH: 1

freebsd_12_task:
  freebsd_instance:
    image: freebsd-12-1-release-amd64
  install_script:
    pkg install -y gettext gmake cmake
#  create_user_script:
#    - pw useradd git
#    - chown -R git:git .
  build_script:
    - ls -la
    - set
    - env
    - cd audacity
    - cat | bash
      echo "inside script"
      exit 0



