#
# Audacity Travis-CI Configuration
#
# The common configuration for all targets goes here.
# Specific configuration goes in scripts/travis.sh
#
# Build logs: https://travis-ci.org/audacity/audacity
#
language: cpp

# need sudo to install packages
sudo: required

# linux build needs gcc 4.9 or later
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9
            - gcc-4.9
            - gettext
            - autopoint
env:
   matrix:
      - TARGET=linux-x86_64
      - TARGET=windows-i686
      - TARGET=windows-x86_64

before_install:
   # bake version info into binary
   - git show -s --format="#define REV_LONG \"%H\"%n#define REV_TIME \"%cd\"%n" | tee ./src/RevisionIdent.h
   - ./scripts/travis.sh before_install

before_script:
   - ./scripts/travis.sh before_script

script:
   - autoreconf --no-recursive --install --force
   - ./scripts/travis.sh script
